name: goreleaser

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'select tag'
        required: true
        type: string

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      -
        name: Checkout tag if provided
        if: github.event.inputs.tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Test
        uses: joerdav/run-xc@v1.1.0
        with:
          task: test
          version: v0.8.5

      -
        name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.BREW_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
  flake:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: Install NIX
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Update Flake
        uses: joerdav/run-xc@v1.1.0
        with:
          version: v0.8.5
          task: update-nix
      -
        name: Add and Commit
        run: |
          git config --global user.name 'joerdav'
          git config --global user.email 'joe.davidson.21111@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout main
          git commit -am "[Automated]: Update Nix Flake"
          git push
